# Generated by Django 4.1.1 on 2022-09-29 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('napp', '0002_alter_mobilecustamisation_customorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilecustamisation',
            name='customorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
