# Generated by Django 4.1.1 on 2022-10-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('napp', '0003_alter_mobilecustamisation_customorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilecustamisation',
            name='customorID',
            field=models.IntegerField(),
        ),
    ]
