# Generated by Django 4.1.1 on 2022-10-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('napp', '0004_alter_mobilecustamisation_customorid'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_prise', models.IntegerField()),
                ('productId', models.IntegerField()),
                ('address', models.TextField(max_length=500)),
            ],
        ),
    ]
