# Generated by Django 4.1.2 on 2022-10-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('napp', '0005_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
