# Generated by Django 4.1.2 on 2022-10-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('napp', '0007_rename_total_prise_buy_customorid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='prise',
            field=models.IntegerField(default=1),
        ),
    ]
